# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "hello world" # run the `echo` command
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: ./
          paths: build
  deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - attach_workspace:
          at: ./build
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config user.email "michaelalexnguyen@gmail.com"
            git config user.name "Michael Nguyen"
      - add_ssh_keys:
          fingerprints:
            - "58:41:7d:b8:54:ba:57:b8:69:1e:f9:73:3d:4b:1e:db"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist ./build

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
