version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config user.email "michaelalexnguyen@gmail.com"
            git config user.name "Michael Nguyen"
      - add_ssh_keys:
          fingerprints:
            - "58:41:7d:b8:54:ba:57:b8:69:1e:f9:73:3d:4b:1e:db"
      - run:
          name: Deploy to master branch
          command: gh-pages -b master -t -m "[skip ci] Updates" -d build
