version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - persist_to_workspace:
          root: ./
          paths: build
  deploy:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config user.email "michaelalexnguyen@gmail.com"
            git config user.name "Michael Nguyen"
      - add_ssh_keys:
          fingerprints:
            - "58:41:7d:b8:54:ba:57:b8:69:1e:f9:73:3d:4b:1e:db"
      - run:
          name: Deploy to master branch
          command: gh-pages -b master -t -m "[skip ci] Updates" -d build

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
